### ISSUE TITLE
sdist setup.py  fails

### ISSUE THREAD

**Issue by jayvdb** [althonos/jinja2-fsloader#1]
Installing from the sdist is failing when building an rpm for openSUSE.

```py
[   60s] + /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
[   61s] Traceback (most recent call last):
[   61s]   File "setup.py", line 5, in <module>
[   61s]     setuptools.setup()
[   61s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
[   61s]     return distutils.core.setup(**attrs)
[   61s]   File "/usr/lib64/python2.7/distutils/core.py", line 124, in setup
[   61s]     dist.parse_config_files()
[   61s]   File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 698, in parse_config_files
[   61s]     ignore_option_errors=ignore_option_errors)
[   61s]   File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 120, in parse_configuration
[   61s]     meta.parse()
[   61s]   File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 425, in parse
[   61s]     section_parser_method(section_options)
[   61s]   File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 398, in parse_section
[   61s]     self[name] = value
[   61s]   File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 183, in __setitem__
[   61s]     value = parser(value)
[   61s]   File "/usr/lib/python2.7/site-packages/setuptools/config.py", line 509, in _parse_version
[   61s]     raise DistutilsOptionError(tmpl.format(**locals()))
[   61s] distutils.errors.DistutilsOptionError: Version loaded from file: jinja2_fsloader/_version.txt does not comply with PEP 440:
```
c.f. https://build.opensuse.org/package/show/home:jayvdb:pyfs/python-jinja2-fsloader

I am able to get around the problem with a bit of `sed`, but others may not be so lucky.

**Comment by althonos** [comment]
@jayvdb: My bad ! I forgot to add a manifest to embed the `_version.txt` file. `v0.1.1` now has one and should install just fine in both wheel and sdist.

**Comment by jayvdb** [comment]
fyi, `python2 setup.py test` fails.

once when encountering `from .utils import ..` easy to workaround and then this one I forgot how to workaround.

```
python2 setup.py test
[   41s] running test
[   41s] running egg_info
[   42s] writing requirements to jinja2_fsloader.egg-info/requires.txt
[   42s] writing jinja2_fsloader.egg-info/PKG-INFO
[   42s] writing top-level names to jinja2_fsloader.egg-info/top_level.txt
[   42s] writing dependency_links to jinja2_fsloader.egg-info/dependency_links.txt
[   42s] reading manifest file 'jinja2_fsloader.egg-info/SOURCES.txt'
[   42s] reading manifest template 'MANIFEST.in'
[   42s] writing manifest file 'jinja2_fsloader.egg-info/SOURCES.txt'
[   42s] running build_ext
[   42s] Traceback (most recent call last):
[   42s]   File "setup.py", line 5, in <module>
[   42s]     setuptools.setup()
[   42s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
[   42s]     return distutils.core.setup(**attrs)
[   42s]   File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
[   42s]     dist.run_commands()
[   42s]   File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
[   42s]     self.run_command(cmd)
[   42s]   File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
[   42s]     cmd_obj.run()
[   42s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 229, in run
[   42s]     self.run_tests()
[   42s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 251, in run_tests
[   42s]     exit=False,
[   42s]   File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
[   42s]     self.parseArgs(argv)
[   42s]   File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
[   42s]     self.createTests()
[   42s]   File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
[   42s]     self.module)
[   42s]   File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
[   42s]     suites = [self.loadTestsFromName(name, module) for name in names]
[   42s]   File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
[   42s]     return self.loadTestsFromModule(obj)
[   42s]   File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
[   42s]     tests.append(self.loadTestsFromName(submodule))
[   42s]   File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
[   42s]     parent, obj = obj, getattr(obj, part)
[   42s] AttributeError: 'module' object has no attribute 'test_fsloader'
```

`python3 setup.py test` works well.

I do have `green` packaged, as I've used it myself for other projects, but it has a packaging bug I want to get fixed before submitting, so I am going to try using pytest.

**Comment by jayvdb** [comment]
I think the problem was that `mock` isnt declared as a test dependency

**Comment by jayvdb** [comment]
Yup; that was it.
